### ISSUE TITLE
How to choose the training set

### ISSUE THREAD

**Issue by Honlan** [donydchen/ganimation_replicate#9]
Thanks a lot for your replication.

As you know, the EmotioNet dataset contains more than 90W images, which are diverse in quality.

The author uses 20W for training, and you use more than 40W for training.

So may I ask how do you choose the training set? Do you use any strategy to choose or filter some "good" images?

Thanks again.

**Comment by donydchen** [comment]
As per the email I reply, let me attach the content here for the convenience of others who may have the same doubt. 

---

I employed the python package `face_recognition` to extract human face and then used `Openface` to extract Action Units vectors. So those images that meet the above two requirements, retained, while those cannot detect any face nor AU vector, removed.

Besides, I remember that using `Openface` to extract AU vectors really takes time, in order to save time, I only ran the extraction program for few days, and stopped the program at will, which results in around 400k images.

**Comment by Honlan** [comment]
Get it. Thanks a lot for you reply.
